Repository GSA/code-gov-front-end, pull requests merged in 2020-04, with the labels that each got.

#366 snyk updates
  config/webpack/webpack.prod.js
  config/webpack/webpack.shared.js
  package-lock.json
  package.json
Labels: [area] security, [effort] medium

#371 roadmap updates to 4/7/2020
  config/site/site.json
  src/components/roadmap/__snapshots__/roadmap.container.test.js.snap
Labels: [effort] small, [priority] low

#373 Update news with SSA blog post
  .snyk
  assets/img/news/ssa_hackathon.jpeg
  config/site/site.json
  src/components/home-news/__snapshots__/home-news.container.test.js.snap
Labels: [effort] small, [issue-type] enhancement

#375 Use .nvmrc to define node version
  .nvmrc
Labels: [effort] small, [issue-type] enhancement

#369 Convert compliance dashboard web component to react component
  config/webpack/webpack.shared.js
  dependency_licenses.json
  package-lock.json
  package.json
  src/components/about-page/__snapshots__/about-page.test.js.snap
  src/components/about-page/__snapshots__/compliance-dashboard.component.test.js.snap
  src/components/about-page/about-page.test.js
  src/components/about-page/compliance-dashboard.component.js
  src/components/about-page/compliance-dashboard.component.test.js
  src/components/about-page/compliance-dashboard.container.js
  src/components/about-page/index.js
  styles/_main.scss
  styles/compliance-dashboard.scss
Labels: [effort] medium, [issue-type] enhancement

#374 Content updates to README
  README.md
Labels: [area] docs, [effort] small

#377 Updated nvm text from 10.15.1 to 10.19.0
  README.md
Labels: [area] docs, [effort] small

#380 Update compliance dashboard cypress test
  cypress/integration/compliance-dashboard-direct-nav.spec.js
Labels: [area] security, [effort] small

#383 Enable Federalist previews
  config/webpack/webpack.shared.js
  src/browser-history.js
  src/components/about-page/index.js
  src/components/app/__snapshots__/app.component.test.js.snap
  src/components/app/app.component.js
  src/components/footer/footer.container.js
  src/components/menu/__snapshots__/menu.container.test.js.snap
  src/components/menu/menu.container.js
  src/components/mobile-menu-control/__snapshots__/mobile-menu-control.container.test.js.snap
  src/components/mobile-menu-control/mobile-menu-control.container.js
  src/utils/other.js
  styles/theme/_uswds-theme-general.scss
  styles/theme/_uswds-theme-typography.scss
Labels: [area] platform, [effort] medium

#382 Code-gov-font npm bump
  package-lock.json
  package.json
Labels: [area] security, [effort] small

#389 Removing json-schema-validation web component
  config/site/site.json
  config/webpack/webpack.shared.js
  dependency_licenses.json
  package-lock.json
  package.json
  src/components/about-page/__snapshots__/about-page.test.js.snap
  src/components/about-page/about-page.test.js
  src/components/about-page/html/compliance/how-to-inventory-b.html
  src/components/about-page/index.js
  src/components/about-page/json-validator.component.js
  src/components/menu/__snapshots__/menu.container.test.js.snap
  src/components/mobile-menu/__snapshots__/mobile-menu.container.test.js.snap
Labels: [area] enhancement, [effort] small, [issue-type] enhancement

#391 Testing 1.2.0 changes on stage
  .circleci/config.yml
  README.md
  assets/img/news/summer_fellow.jpeg
  config/site/site.json
  config/webpack/webpack.shared.js
  cypress/integration/compliance-dashboard-direct-nav.spec.js
  dependency_licenses.json
  package-lock.json
  package.json
  src/browser-history.js
  src/components/about-page/__snapshots__/about-page.test.js.snap
  src/components/about-page/about-page.test.js
  src/components/about-page/html/compliance/how-to-inventory-b.html
  src/components/about-page/index.js
  src/components/about-page/json-validator.component.js
  src/components/app/__snapshots__/app.component.test.js.snap
  src/components/app/app.component.js
  src/components/footer/footer.container.js
  src/components/home-news/__snapshots__/home-news.container.test.js.snap
  src/components/menu/__snapshots__/menu.container.test.js.snap
  src/components/menu/menu.container.js
  src/components/mobile-menu-control/__snapshots__/mobile-menu-control.container.test.js.snap
  src/components/mobile-menu-control/mobile-menu-control.container.js
  src/components/mobile-menu/__snapshots__/mobile-menu.container.test.js.snap
  src/components/project-page/project-page.component.js
  src/components/project-page/project-page.component.test.js
  src/utils/other.js
  src/utils/repo-parsing.js
  styles/theme/_uswds-theme-general.scss
  styles/theme/_uswds-theme-typography.scss
Labels: [area] platform, [effort] small
