Repository GSA/code-gov-front-end, pull requests merged in 2020-09, with the labels that each got.

#486 Updated news - 09292020
  .snyk
  assets/img/news/accessibility.jpeg
  assets/img/news/ai.jpg
  assets/img/news/bday.jpeg
  assets/img/news/rayvn.jpeg
  assets/img/news/sara.jpeg
  config/site/site.json
  config/webpack/webpack.shared.js
  cypress/integration/browse-projects-direct-nav.spec.js
  package-lock.json
  src/components/home-news/__snapshots__/home-news.container.test.js.snap
Labels: [area] enhancement, [area] security, [effort] small

#487 Updated and reviewed dependencies
  package-lock.json
  package.json
Labels: [area] security

#490 Updated link in AI section.
  src/components/federal-agencies/html/compliance/data-assets-ai.html
Labels: [area] enhancement

#492 Bumped api-client to 0.4.2 in FE package.json
  package-lock.json
  package.json
Labels: [area] security

#494 Sitemap updates in FE package.json
  package-lock.json
  package.json
Labels: [area] enhancement

#497 Final Fall release testing, update to Cypress test for project nav
  assets/data/filters/tasks.json
  cypress/integration/browse-projects-direct-nav.spec.js
  package-lock.json
  package.json
Labels: [area] security

#498 Testing latest release on staging
  .snyk
  assets/data/filters/tasks.json
  assets/img/news/accessibility.jpeg
  assets/img/news/ai.jpg
  assets/img/news/bday.jpeg
  assets/img/news/rayvn.jpeg
  assets/img/news/sara.jpeg
  config/site/site.json
  config/webpack/webpack.shared.js
  cypress/integration/browse-projects-direct-nav.spec.js
  package-lock.json
  package.json
  src/components/federal-agencies/html/compliance/data-assets-ai.html
  src/components/home-news/__snapshots__/home-news.container.test.js.snap
  styles/theme/styles.scss
Labels: [area] platform
